/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsSetConversationPrefsErrorSchema : Schema for error response from admin.conversations.setConversationPrefs



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsSetConversationPrefsErrorSchema {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl AdminConversationsSetConversationPrefsErrorSchema {
    /// Schema for error response from admin.conversations.setConversationPrefs
    pub fn new(error: Error, ok: crate::models::DefsOkFalse) -> AdminConversationsSetConversationPrefsErrorSchema {
        AdminConversationsSetConversationPrefsErrorSchema {
            error,
            ok,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "feature_not_enabled")]
    FeatureNotEnabled,
    #[serde(rename = "not_an_admin")]
    NotAnAdmin,
    #[serde(rename = "channel_not_found")]
    ChannelNotFound,
    #[serde(rename = "channel_type_not_supported")]
    ChannelTypeNotSupported,
    #[serde(rename = "restricted_action")]
    RestrictedAction,
    #[serde(rename = "missing_scope")]
    MissingScope,
    #[serde(rename = "could_not_set_channel_pref")]
    CouldNotSetChannelPref,
    #[serde(rename = "default_org_wide_channel")]
    DefaultOrgWideChannel,
}

impl Default for Error {
    fn default() -> Error {
        Self::FeatureNotEnabled
    }
}

