/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsGetTeamsErrorSchema : Schema for error response from admin.conversations.getTeams



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsGetTeamsErrorSchema {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl AdminConversationsGetTeamsErrorSchema {
    /// Schema for error response from admin.conversations.getTeams
    pub fn new(error: Error, ok: crate::models::DefsOkFalse) -> AdminConversationsGetTeamsErrorSchema {
        AdminConversationsGetTeamsErrorSchema {
            error,
            ok,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "feature_not_enabled")]
    FeatureNotEnabled,
    #[serde(rename = "channel_not_found")]
    ChannelNotFound,
    #[serde(rename = "channel_type_not_supported")]
    ChannelTypeNotSupported,
    #[serde(rename = "unsupported_team_type")]
    UnsupportedTeamType,
    #[serde(rename = "restricted_action")]
    RestrictedAction,
    #[serde(rename = "could_not_get_teams")]
    CouldNotGetTeams,
    #[serde(rename = "invalid_cursor")]
    InvalidCursor,
    #[serde(rename = "invalid_limit")]
    InvalidLimit,
}

impl Default for Error {
    fn default() -> Error {
        Self::FeatureNotEnabled
    }
}

