/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsCreateSchema : Schema for successful response of admin.conversations.create



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsCreateSchema {
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
}

impl AdminConversationsCreateSchema {
    /// Schema for successful response of admin.conversations.create
    pub fn new(ok: crate::models::DefsOkTrue) -> AdminConversationsCreateSchema {
        AdminConversationsCreateSchema {
            channel_id: None,
            ok,
        }
    }
}


