/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsCreateErrorSchema : Schema for error response from admin.conversations.create



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsCreateErrorSchema {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl AdminConversationsCreateErrorSchema {
    /// Schema for error response from admin.conversations.create
    pub fn new(error: Error, ok: crate::models::DefsOkFalse) -> AdminConversationsCreateErrorSchema {
        AdminConversationsCreateErrorSchema {
            error,
            ok,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "feature_not_enabled")]
    FeatureNotEnabled,
    #[serde(rename = "name_taken")]
    NameTaken,
    #[serde(rename = "restricted_action")]
    RestrictedAction,
    #[serde(rename = "team_not_found")]
    TeamNotFound,
    #[serde(rename = "invalid_team")]
    InvalidTeam,
    #[serde(rename = "invalid_name")]
    InvalidName,
    #[serde(rename = "could_not_create_channel")]
    CouldNotCreateChannel,
    #[serde(rename = "team_id_or_org_required")]
    TeamIdOrOrgRequired,
}

impl Default for Error {
    fn default() -> Error {
        Self::FeatureNotEnabled
    }
}

