/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsInviteErrorSchema : Schema for error response from admin.conversations.invite



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsInviteErrorSchema {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl AdminConversationsInviteErrorSchema {
    /// Schema for error response from admin.conversations.invite
    pub fn new(error: Error, ok: crate::models::DefsOkFalse) -> AdminConversationsInviteErrorSchema {
        AdminConversationsInviteErrorSchema {
            error,
            ok,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "feature_not_enabled")]
    FeatureNotEnabled,
    #[serde(rename = "channel_not_found")]
    ChannelNotFound,
    #[serde(rename = "channel_type_not_supported")]
    ChannelTypeNotSupported,
    #[serde(rename = "default_org_wide_channel")]
    DefaultOrgWideChannel,
    #[serde(rename = "restricted_action")]
    RestrictedAction,
    #[serde(rename = "user_must_be_admin")]
    UserMustBeAdmin,
    #[serde(rename = "failed_for_some_users")]
    FailedForSomeUsers,
}

impl Default for Error {
    fn default() -> Error {
        Self::FeatureNotEnabled
    }
}

