/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsSearchSchema : Schema for successful response of admin.conversations.search



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsSearchSchema {
    #[serde(rename = "channels")]
    pub channels: Vec<crate::models::ObjsChannel>,
    #[serde(rename = "next_cursor")]
    pub next_cursor: String,
}

impl AdminConversationsSearchSchema {
    /// Schema for successful response of admin.conversations.search
    pub fn new(channels: Vec<crate::models::ObjsChannel>, next_cursor: String) -> AdminConversationsSearchSchema {
        AdminConversationsSearchSchema {
            channels,
            next_cursor,
        }
    }
}


