/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsGetConversationPrefsSchema : Schema for successful response of admin.conversations.getConversationPrefs



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsGetConversationPrefsSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "prefs", skip_serializing_if = "Option::is_none")]
    pub prefs: Option<Box<crate::models::AdminConversationsGetConversationPrefsSchemaPrefs>>,
}

impl AdminConversationsGetConversationPrefsSchema {
    /// Schema for successful response of admin.conversations.getConversationPrefs
    pub fn new(ok: crate::models::DefsOkTrue) -> AdminConversationsGetConversationPrefsSchema {
        AdminConversationsGetConversationPrefsSchema {
            ok,
            prefs: None,
        }
    }
}


