/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsGetConversationPrefsSchemaPrefs {
    #[serde(rename = "can_thread", skip_serializing_if = "Option::is_none")]
    pub can_thread: Option<Box<crate::models::AdminConversationsGetConversationPrefsSchemaPrefsCanThread>>,
    #[serde(rename = "who_can_post", skip_serializing_if = "Option::is_none")]
    pub who_can_post: Option<Box<crate::models::AdminConversationsGetConversationPrefsSchemaPrefsCanThread>>,
}

impl AdminConversationsGetConversationPrefsSchemaPrefs {
    pub fn new() -> AdminConversationsGetConversationPrefsSchemaPrefs {
        AdminConversationsGetConversationPrefsSchemaPrefs {
            can_thread: None,
            who_can_post: None,
        }
    }
}


