/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsGetTeamsSchema : Schema for successful response of admin.conversations.getTeams



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsGetTeamsSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "response_metadata", skip_serializing_if = "Option::is_none")]
    pub response_metadata: Option<Box<crate::models::AdminConversationsGetTeamsSchemaResponseMetadata>>,
    #[serde(rename = "team_ids")]
    pub team_ids: Vec<String>,
}

impl AdminConversationsGetTeamsSchema {
    /// Schema for successful response of admin.conversations.getTeams
    pub fn new(ok: crate::models::DefsOkTrue, team_ids: Vec<String>) -> AdminConversationsGetTeamsSchema {
        AdminConversationsGetTeamsSchema {
            ok,
            response_metadata: None,
            team_ids,
        }
    }
}


