/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminConversationsArchiveErrorSchema : Schema for error response from admin.conversations.archive



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminConversationsArchiveErrorSchema {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl AdminConversationsArchiveErrorSchema {
    /// Schema for error response from admin.conversations.archive
    pub fn new(error: Error, ok: crate::models::DefsOkFalse) -> AdminConversationsArchiveErrorSchema {
        AdminConversationsArchiveErrorSchema {
            error,
            ok,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "feature_not_enabled")]
    FeatureNotEnabled,
    #[serde(rename = "channel_not_found")]
    ChannelNotFound,
    #[serde(rename = "channel_type_not_supported")]
    ChannelTypeNotSupported,
    #[serde(rename = "default_org_wide_channel")]
    DefaultOrgWideChannel,
    #[serde(rename = "already_archived")]
    AlreadyArchived,
    #[serde(rename = "cant_archive_general")]
    CantArchiveGeneral,
    #[serde(rename = "restricted_action")]
    RestrictedAction,
    #[serde(rename = "could_not_archive_channel")]
    CouldNotArchiveChannel,
}

impl Default for Error {
    fn default() -> Error {
        Self::FeatureNotEnabled
    }
}

