/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ApiPermissionsScopesListSuccessSchema : Schema for successful response api.permissions.scopes.list method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiPermissionsScopesListSuccessSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "scopes")]
    pub scopes: Box<crate::models::ApiPermissionsScopesListSuccessSchemaScopes>,
}

impl ApiPermissionsScopesListSuccessSchema {
    /// Schema for successful response api.permissions.scopes.list method
    pub fn new(ok: crate::models::DefsOkTrue, scopes: crate::models::ApiPermissionsScopesListSuccessSchemaScopes) -> ApiPermissionsScopesListSuccessSchema {
        ApiPermissionsScopesListSuccessSchema {
            ok,
            scopes: Box::new(scopes),
        }
    }
}


