/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AppsPermissionsInfoSchema : Schema for successful response from apps.permissions.info method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppsPermissionsInfoSchema {
    #[serde(rename = "info")]
    pub info: Box<crate::models::AppsPermissionsInfoSchemaInfo>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
}

impl AppsPermissionsInfoSchema {
    /// Schema for successful response from apps.permissions.info method
    pub fn new(info: crate::models::AppsPermissionsInfoSchemaInfo, ok: crate::models::DefsOkTrue) -> AppsPermissionsInfoSchema {
        AppsPermissionsInfoSchema {
            info: Box::new(info),
            ok,
        }
    }
}


