/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BotsInfoSchema : Schema for successful response from bots.info method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BotsInfoSchema {
    #[serde(rename = "bot")]
    pub bot: Box<crate::models::BotsInfoSchemaBot>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
}

impl BotsInfoSchema {
    /// Schema for successful response from bots.info method
    pub fn new(bot: crate::models::BotsInfoSchemaBot, ok: crate::models::DefsOkTrue) -> BotsInfoSchema {
        BotsInfoSchema {
            bot: Box::new(bot),
            ok,
        }
    }
}


