/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BotsInfoSchemaBot {
    #[serde(rename = "app_id")]
    pub app_id: String,
    #[serde(rename = "deleted")]
    pub deleted: bool,
    #[serde(rename = "icons")]
    pub icons: Box<crate::models::BotsInfoSchemaBotIcons>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated")]
    pub updated: i32,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl BotsInfoSchemaBot {
    pub fn new(app_id: String, deleted: bool, icons: crate::models::BotsInfoSchemaBotIcons, id: String, name: String, updated: i32) -> BotsInfoSchemaBot {
        BotsInfoSchemaBot {
            app_id,
            deleted,
            icons: Box::new(icons),
            id,
            name,
            updated,
            user_id: None,
        }
    }
}


