/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatScheduleMessageSuccessSchema : Schema for successful response of chat.scheduleMessage method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChatScheduleMessageSuccessSchema {
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "message")]
    pub message: Box<crate::models::ChatScheduleMessageSuccessSchemaMessage>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "post_at")]
    pub post_at: i32,
    #[serde(rename = "scheduled_message_id")]
    pub scheduled_message_id: String,
}

impl ChatScheduleMessageSuccessSchema {
    /// Schema for successful response of chat.scheduleMessage method
    pub fn new(channel: String, message: crate::models::ChatScheduleMessageSuccessSchemaMessage, ok: crate::models::DefsOkTrue, post_at: i32, scheduled_message_id: String) -> ChatScheduleMessageSuccessSchema {
        ChatScheduleMessageSuccessSchema {
            channel,
            message: Box::new(message),
            ok,
            post_at,
            scheduled_message_id,
        }
    }
}


