/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatUpdateSuccessSchema : Schema for successful response of chat.update method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChatUpdateSuccessSchema {
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "message")]
    pub message: Box<crate::models::MessageObject>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "ts")]
    pub ts: String,
}

impl ChatUpdateSuccessSchema {
    /// Schema for successful response of chat.update method
    pub fn new(channel: String, message: crate::models::MessageObject, ok: crate::models::DefsOkTrue, text: String, ts: String) -> ChatUpdateSuccessSchema {
        ChatUpdateSuccessSchema {
            channel,
            message: Box::new(message),
            ok,
            text,
            ts,
        }
    }
}


