/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatMeMessageSchema : Schema for successful response from chat.meMessage method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChatMeMessageSchema {
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<String>,
}

impl ChatMeMessageSchema {
    /// Schema for successful response from chat.meMessage method
    pub fn new(ok: crate::models::DefsOkTrue) -> ChatMeMessageSchema {
        ChatMeMessageSchema {
            channel: None,
            ok,
            ts: None,
        }
    }
}


