/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatScheduledMessagesListSchema : Schema for successful response from chat.scheduledMessages.list method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChatScheduledMessagesListSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "response_metadata")]
    pub response_metadata: Box<crate::models::AdminConversationsGetTeamsSchemaResponseMetadata>,
    #[serde(rename = "scheduled_messages")]
    pub scheduled_messages: Vec<crate::models::ChatScheduledMessagesListSchemaScheduledMessages>,
}

impl ChatScheduledMessagesListSchema {
    /// Schema for successful response from chat.scheduledMessages.list method
    pub fn new(ok: crate::models::DefsOkTrue, response_metadata: crate::models::AdminConversationsGetTeamsSchemaResponseMetadata, scheduled_messages: Vec<crate::models::ChatScheduledMessagesListSchemaScheduledMessages>) -> ChatScheduledMessagesListSchema {
        ChatScheduledMessagesListSchema {
            ok,
            response_metadata: Box::new(response_metadata),
            scheduled_messages,
        }
    }
}


