/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatPostMessageSuccessSchema : Schema for successful response of chat.postMessage method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChatPostMessageSuccessSchema {
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "message")]
    pub message: Box<crate::models::ObjsMessage>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "ts")]
    pub ts: String,
}

impl ChatPostMessageSuccessSchema {
    /// Schema for successful response of chat.postMessage method
    pub fn new(channel: String, message: crate::models::ObjsMessage, ok: crate::models::DefsOkTrue, ts: String) -> ChatPostMessageSuccessSchema {
        ChatPostMessageSuccessSchema {
            channel,
            message: Box::new(message),
            ok,
            ts,
        }
    }
}


