/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ConversationsRepliesSuccessSchema : Schema for successful response from conversations.replies method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConversationsRepliesSuccessSchema {
    #[serde(rename = "has_more", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    #[serde(rename = "messages")]
    pub messages: Vec<serde_json::Value>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
}

impl ConversationsRepliesSuccessSchema {
    /// Schema for successful response from conversations.replies method
    pub fn new(messages: Vec<serde_json::Value>, ok: crate::models::DefsOkTrue) -> ConversationsRepliesSuccessSchema {
        ConversationsRepliesSuccessSchema {
            has_more: None,
            messages,
            ok,
        }
    }
}


