/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ConversationsLeaveSuccessSchema : Schema for successful response from conversations.leave method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConversationsLeaveSuccessSchema {
    #[serde(rename = "not_in_channel", skip_serializing_if = "Option::is_none")]
    pub not_in_channel: Option<bool>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
}

impl ConversationsLeaveSuccessSchema {
    /// Schema for successful response from conversations.leave method
    pub fn new(ok: crate::models::DefsOkTrue) -> ConversationsLeaveSuccessSchema {
        ConversationsLeaveSuccessSchema {
            not_in_channel: None,
            ok,
        }
    }
}


