/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DefaultErrorTemplate : This method either only returns a brief _not OK_ response or a verbose schema is not available for this method.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DefaultErrorTemplate {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl DefaultErrorTemplate {
    /// This method either only returns a brief _not OK_ response or a verbose schema is not available for this method.
    pub fn new(ok: crate::models::DefsOkFalse) -> DefaultErrorTemplate {
        DefaultErrorTemplate {
            ok,
        }
    }
}


