/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DefsOkTrue {
    #[serde(rename = "true")]
    _True,

}

impl ToString for DefsOkTrue {
    fn to_string(&self) -> String {
        match self {
            Self::_True => String::from("true"),
        }
    }
}

impl Default for DefsOkTrue {
    fn default() -> DefsOkTrue {
        Self::_True
    }
}




