/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FilesListSchema : Schema for successful response from files.list method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FilesListSchema {
    #[serde(rename = "files")]
    pub files: Vec<crate::models::ObjsFile>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "paging")]
    pub paging: Box<crate::models::ObjsPaging>,
}

impl FilesListSchema {
    /// Schema for successful response from files.list method
    pub fn new(files: Vec<crate::models::ObjsFile>, ok: crate::models::DefsOkTrue, paging: crate::models::ObjsPaging) -> FilesListSchema {
        FilesListSchema {
            files,
            ok,
            paging: Box::new(paging),
        }
    }
}


