/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RemindersListSchema : Schema for successful response from reminders.list method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RemindersListSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "reminders")]
    pub reminders: Vec<crate::models::ObjsReminder>,
}

impl RemindersListSchema {
    /// Schema for successful response from reminders.list method
    pub fn new(ok: crate::models::DefsOkTrue, reminders: Vec<crate::models::ObjsReminder>) -> RemindersListSchema {
        RemindersListSchema {
            ok,
            reminders,
        }
    }
}


