/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TeamInfoSchema : Schema for successful response from team.info method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamInfoSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "team")]
    pub team: Box<crate::models::ObjsTeam>,
}

impl TeamInfoSchema {
    /// Schema for successful response from team.info method
    pub fn new(ok: crate::models::DefsOkTrue, team: crate::models::ObjsTeam) -> TeamInfoSchema {
        TeamInfoSchema {
            ok,
            team: Box::new(team),
        }
    }
}


