/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TeamAccessLogsSchema : Schema for successful response from team.accessLogs method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamAccessLogsSchema {
    #[serde(rename = "logins")]
    pub logins: Vec<crate::models::TeamAccessLogsSchemaLogins>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "paging")]
    pub paging: Box<crate::models::ObjsPaging>,
}

impl TeamAccessLogsSchema {
    /// Schema for successful response from team.accessLogs method
    pub fn new(logins: Vec<crate::models::TeamAccessLogsSchemaLogins>, ok: crate::models::DefsOkTrue, paging: crate::models::ObjsPaging) -> TeamAccessLogsSchema {
        TeamAccessLogsSchema {
            logins,
            ok,
            paging: Box::new(paging),
        }
    }
}


