/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UsersSetPhotoSchema : Schema for successful response from users.setPhoto method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsersSetPhotoSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "profile")]
    pub profile: Box<crate::models::UsersSetPhotoSchemaProfile>,
}

impl UsersSetPhotoSchema {
    /// Schema for successful response from users.setPhoto method
    pub fn new(ok: crate::models::DefsOkTrue, profile: crate::models::UsersSetPhotoSchemaProfile) -> UsersSetPhotoSchema {
        UsersSetPhotoSchema {
            ok,
            profile: Box::new(profile),
        }
    }
}


