/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UsergroupsListSchema : Schema for successful response from usergroups.list method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsergroupsListSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "usergroups")]
    pub usergroups: Vec<crate::models::ObjsSubteam>,
}

impl UsergroupsListSchema {
    /// Schema for successful response from usergroups.list method
    pub fn new(ok: crate::models::DefsOkTrue, usergroups: Vec<crate::models::ObjsSubteam>) -> UsergroupsListSchema {
        UsergroupsListSchema {
            ok,
            usergroups,
        }
    }
}


